[package]
name = "sigh"
description = "HTTP signature generation and verification for ActivityPub"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
reqwest = "0.11"
nom = "7"
openssl = "0.10"
base64 = "0.13"
